name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '23.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Use Node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v4.3.0
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci
      - run: npm run lint
